// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import AlertDialogController from "./alert_dialog_controller"
application.register("alert-dialog", AlertDialogController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DismissableController from "./dismissable_controller"
application.register("dismissable", DismissableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InputController from "./input_controller"
application.register("input", InputController)

import SheetController from "./sheet_controller"
application.register("sheet", SheetController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ToggleThemeController from "./toggle_theme_controller"
application.register("toggle-theme", ToggleThemeController)
