// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ColorThemeController from "./color_theme_controller"
application.register("color-theme", ColorThemeController)

import LottieController from "./lottie_controller"
application.register("lottie", LottieController)
