/**
 * IMPORTANT: DO NOT EDIT THIS FILE MANUALLY
 * --------------------------------------------
 * This file is automatically generated and managed.
 *
 * Last updated: 2024-09-23 17:09:40
 */

// Load and export all of the stimulus controllers
import { Application } from "@hotwired/stimulus";

const application = Application.start();

// Configure Stimulus development experience
application.debug = false;
window.Stimulus = application;

import { application as RBUI } from "rbui-js";

// Import all controller files
import PopoverController from "./popover/popover_controller";

// Register all controllers
RBUI.unload("rbui--popover");
application.register("rbui--popover", PopoverController);

// Export application
export { application };
