/**
 * IMPORTANT: DO NOT EDIT THIS FILE MANUALLY
 * --------------------------------------------
 * This file is automatically generated and managed.
 * 
 * Last updated: 2024-09-22 12:53:55
 */

// Load and export all of the stimulus controllers
import { Application } from "@hotwired/stimulus";

const application = Application.start();

// Configure Stimulus development experience
application.debug = false;
window.Stimulus = application;

import { application as RBUI } from "rbui-js";

// Import all controller files
import ComboboxContentController from "./combobox/combobox_content_controller";
import ComboboxController from "./combobox/combobox_controller";
import ComboboxItemController from "./combobox/combobox_item_controller";
import CommandController from "./command/command_controller";
import CommandDialogController from "./command/command_dialog_controller";

// Register all controllers
RBUI.unload("rbui--combobox");
application.register("rbui--combobox", ComboboxController);
RBUI.unload("rbui--combobox-content");
application.register("rbui--combobox-content", ComboboxContentController);
RBUI.unload("rbui--combobox-item");
application.register("rbui--combobox-item", ComboboxItemController);
RBUI.unload("rbui--command");
application.register("rbui--command", CommandController);
RBUI.unload("rbui--command-dialog");
application.register("rbui--command-dialog", CommandDialogController);


application.register("rbui--command-dialog", CommandDialogController);

// Export all controllers so user of npm package can lazy load controllers
export { default as ComboboxContentController } from "./combobox/combobox_content_controller";
export { default as ComboboxController } from "./combobox/combobox_controller";
export { default as ComboboxItemController } from "./combobox/combobox_item_controller";
export { default as CommandController } from "./command/command_controller";
export { default as CommandDialogController } from "./command/command_dialog_controller";

// Export application
export { application };


